version: '3.8'

services:
  bot_image:
    build: ./bot
    restart: always
    depends_on:
      db_image:
        condition: service_healthy
    networks:
      app_network:
        ipv4_address: 172.25.0.3
    environment:
      - TOKEN=${TOKEN}
      - RM_HOST=${RM_HOST}
      - RM_PORT=${RM_PORT}
      - RM_USER=${RM_USER}
      - RM_PASSWORD=${RM_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  db_image:
    build: ./db_image
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_REPL_USER=${DB_REPL_USER}
      - DB_REPL_PASSWORD=${DB_REPL_PASSWORD}
      - RM_USER=${RM_USER}
      - RM_PASSWORD=${RM_PASSWORD}
      - RM_PORT=${RM_PORT}
    networks:
      app_network:
        ipv4_address: 172.25.0.2

  db_repl_image:
    build: ./db_repl_image
    restart: always
    depends_on:
      - db_image
    environment:
      - POSTGRES_USER=${DB_REPL_USER}
      - POSTGRES_PASSWORD=${DB_REPL_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - DB_REPL_USER=${DB_REPL_USER}
      - DB_REPL_PASSWORD=${DB_REPL_PASSWORD}
      - DB_HOST=${DB_HOST}  # Это имя хоста мастера для подключения
      - DB_REPL_PORT=${DB_REPL_PORT}
      - DB_DATABASE=${DB_DATABASE}
    networks:
      app_network:
        ipv4_address: 172.25.0.4

networks:
  app_network:
    ipam:
      config:
        - subnet: "172.25.0.0/16"
