CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL
);

CREATE TABLE phone_numbers (
    id SERIAL PRIMARY KEY,
    phone_number VARCHAR(20) NOT NULL
);

CREATE ROLE %DB_REPL_USER% REPLICATION LOGIN PASSWORD '%DB_REPL_PASSWORD%';
SET CLIENT_ENCODING TO 'UTF8';