- name: Configure replication settings
  block:
    - name: Stop PostgreSQL service before configuration
      systemd:
        name: postgresql
        state: stopped

    - name: Clean PGDATA directory
      file:
        path: "{{ pgdata }}"
        state: absent

    - name: Recreate PGDATA directory
      file:
        path: "{{ pgdata }}"
        state: directory
        owner: postgres
        group: postgres
        mode: 0700

    - name: Synchronize data from master
      shell: |
        export PGPASSWORD='{{ db_repl_password }}'
        pg_basebackup -h {{ db_host }} -D {{ pgdata }} -U {{ db_repl_user }} -P -v --wal-method=stream --write-recovery-conf
        unset PGPASSWORD
      become: yes
      become_user: postgres

    - name: Apply configuration for replication
      template:
        src: standby.conf.j2
        dest: "{{ pgdata }}/postgresql.conf"

    - name: Ensure PostgreSQL is started
      systemd:
        name: postgresql
        state: started
        enabled: yes
  when: inventory_hostname in groups['replicas']
