- name: Update apt package cache
  apt:
    update_cache: yes



- name: Install Python and required packages
  become: yes
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
      - libpq-dev
    state: present
    update_cache: yes

- name: Clone the bot repository
  git:
    repo: 'https://github.com/katet3/pt-start-DevOps-bot-number'
    dest: '/opt/tg-bot'
    force: yes

- name: Create virtual environment
  command:
    cmd: python3 -m venv /opt/tg-bot/venv

- name: Activate virtual environment and install dependencies
  pip:
    requirements: '/opt/tg-bot/requirements.txt'
    virtualenv: '/opt/tg-bot/venv'


- name: Generate .env file for Telegram Bot
  template:
    src: env.j2
    dest: /opt/tg-bot/.env
    owner: root
    group: root
    mode: '0644'

- name: Create tg_bot systemd service unit file
  template:
    src: tg_bot.service.j2
    dest: /etc/systemd/system/tg_bot.service
  notify:
    - Reload systemd

- name: Ensure the bot service is running
  systemd:
    name: tg_bot
    enabled: yes
    state: started
  notify:
    - restart tg_bot
