- name: Install Python and required packages
  apt:
    name:
      - python3
      - python3-pip
    state: present
    update_cache: yes

- name: Clone the bot repository
  git:
    repo: 'https://github.com/katet3/pt-start-DevOps-bot-number'
    dest: '/opt/tg-bot'
    version: 'master'
    force: yes

- name: Install Python dependencies
  pip:
    requirements: '/opt/tg-bot/requirements.txt'
    executable: pip3

- name: Generate .env file for Telegram Bot
  template:
    src: env.j2
    dest: /opt/tg-bot/.env
    owner: root
    group: root
    mode: '0644'

- name: Ensure the bot service is running
  systemd:
    name: tg_bot
    enabled: yes
    state: started
    daemon_reload: yes
    description: 'Telegram Bot Service'
    exec_start: '/usr/bin/python3 /opt/tg-bot/bot.py'
    user: root
    after:
      - network.target
    restart: always
  notify:
    - restart tg_bot
